name: Release node_exporter cli binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release node_exporter cli binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/darwin/windows
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64, armv8]
        exclude:
          - goarch: [arm64, armv8]
            goos: windows
          - goarch: armv8
            goos: darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Release node_exporter cli binaries
        uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./" # go build ./node_exporter.go
          binary_name: "node_exporter"
          ldflags: "-s -w"
          extra_files: LICENSE README.md CHANGELOG.md
